version: '3'

services:
  postgres:
    command: -c log_statement=all
    build: ./docker/db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - 5433:5432

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command:
      - start-dev --health-enabled=true --metrics-enabled=true --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak 

      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    ports:
      - 9090:8080
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - 5672:5672
        - 15672:15672

volumes:
  postgres_data:
